version: '3.9'

services: 
    node_backend:
        container_name: barefoot-nomad
        build: 
            context: .
        ports: 
            - "${PORT}:${PORT}"
        environment: 
            - PORT=${PORT}
            - DATABASE_PORT=5432
            - DEV_DATABASE=${DEV_DATABASE}
            - TEST_DATABASE=${TEST_DATABASE}
            - PRODUCTION_DATABASE=${PRODUCTION_DATABASE}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=node_db
        depends_on: 
            - node_db
    migration_down:
        command: ["npm","run", "down" ]
        build: 
            context: .
        depends_on: 
            - node_db
    migration:
        command: ["npm","run", "migrate" ]
        build: 
            context: .
        depends_on: 
            - migration_down
    seed:
        command: ["npm","run", "seed" ]
        build: 
            context: .
        depends_on: 
            - migration
    node_db:
        container_name: node_db
        image: "postgres:14"
        ports: 
            - "5432"
        environment: 
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DEV_DATABASE}
        volumes: 
            - nps_data:/var/lib/postgresql/data
    
volumes: 
    nps_data: {}